package entity;
// Generated Oct 18, 2016 7:27:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Customes generated by hbm2java
 */
public class Customes  implements java.io.Serializable {


     private Serializable username;
     private Serializable password;
     private Serializable hoten;
     private Boolean gioitinh;
     private Serializable email;
     private Boolean role;

    public Customes() {
    }

	
 
    public Customes(Serializable username, Serializable password, Serializable hoten, Boolean gioitinh, Serializable email, Boolean role) {
       this.username = username;
       this.password = password;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.role = role;
    }
    

   
    public Serializable getUsername() {
        return this.username;
    }
    
    public void setUsername(Serializable username) {
        this.username = username;
    }
    public Serializable getPassword() {
        return this.password;
    }
    
    public void setPassword(Serializable password) {
        this.password = password;
    }
    public Serializable getHoten() {
        return this.hoten;
    }
    
    public void setHoten(Serializable hoten) {
        this.hoten = hoten;
    }
    public Boolean getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Boolean gioitinh) {
        this.gioitinh = gioitinh;
    }
    public Serializable getEmail() {
        return this.email;
    }
    
    public void setEmail(Serializable email) {
        this.email = email;
    }
    public Boolean getRole() {
        return this.role;
    }
    
    public void setRole(Boolean role) {
        this.role = role;
    }

    




}


