package entity;
// Generated Oct 18, 2016 7:27:47 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Serializable code;
     private Serializable name;
     private Double price;

    public Products() {
    }

	
    public Products(Serializable code) {
        this.code = code;
    }
    public Products(Serializable code, Serializable name, Double price) {
       this.code = code;
       this.name = name;
       this.price = price;
    }
   
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Serializable getName() {
        return this.name;
    }
    
    public void setName(Serializable name) {
        this.name = name;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


